--DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
-- CASCADE CONSTRAINTS : 강제 삭제

DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;
DROP TABLE SALGRADE;

CREATE TABLE DEPARTMENT (
    DNO NUMBER(2) CONSTRAINT PK_DEPT PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13));

--DROP TABLE EMPLOYEE;    
CREATE TABLE EMPLOYEE (
    ENO NUMBER(4) CONSTRAINT PK_EMP PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR(9),
    MANAGER NUMBER(4),
    HIREDATE DATE,
    SALARY NUMBER(7,2),
    COMMISSTION NUMBER(7, 2),
    ENO NUMBER(2), CONSTRAINT FK_DNO REFERENCES DEPARTMENT);  
    -- REFERENCES : 외래키(참조키)
    
--DROP TABLE SALGRADE;
CREATE TABLE SALGRADE (
    GRADE NUMBER,
    LOSAL NUMBER,
    HISAL NUMBER);

