// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "type", Target = "~T:AddressTest0222.control.StudentCtrl")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<보류 중>", Scope = "member", Target = "~F:AddressTest0222.control.StudentCtrl.rand")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.arrExit_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrView_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrAdd_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrRand_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrUpdate_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.MainForm_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrDel_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:AddressTest0222.Student.#ctor")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.AddForm.addrOkay_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.DelForm_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.showListView")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.dellistView_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.showupListView")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.ViewForm.initListView")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.ViewForm.showListView")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.ViewForm.listView_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:AddressTest0222.view.MyMenu.mainMenu~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:AddressTest0222.view.MyMenu.updataMenu~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:AddressTest0222.view.MyMenu.delMenu~System.String")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.ViewForm.ViewForm_Load(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.iddel")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~M:AddressTest0222.util.RandData.getId~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.Upaddrinfo")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.alladdrDel_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S1871:Two branches in a conditional structure should not have exactly the same implementation", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.Upaddrinfo")]
[assembly: SuppressMessage("Major Code Smell", "S108:Nested blocks of code should not be left empty", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.MainForm.addrRand_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<보류 중>", Scope = "member", Target = "~P:AddressTest0222.Student.Name")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0308.Ui.DelForm.iddel")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.Upaddrinfo")]
[assembly: SuppressMessage("Minor Code Smell", "S1199:Nested code blocks should not be used", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.Upaddrinfo")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.UpdateForm.showupListView")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<보류 중>", Scope = "member", Target = "~M:Address0303.Ui.ViewForm.showListView")]
